version: 2
jobs:
  build:
    docker:
      - image: node:10-alpine
    working_directory: ~/code
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - run: yarn build